// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TitleNewGameOnly","status":false,"description":"[ ver.2.1.0 ]讓標題畫面直接開始遊戲","parameters":{"startString":"-Press Start-","font":"","fileExistAction":"0","soundEffect":"","adjustY":"0"}}
];
